HB-4556 add validation from 1 to 60 field
hicebank/vitya pull request #22
Opened 2023-03-09 16:45 UTC by doiodl

2023-03-12 23:36 UTC, zhPavel requested changes

2023-03-12 23:36 UTC, zhPavel commented on vitya/payment_order/payments/payments.py
> +    purpose: Optional[str]
Там же 24, а не 25

2023-03-12 23:36 UTC, zhPavel commented on vitya/payment_order/payments/validators.py
> +    allowed_chars_set = set(CHARS_FOR_PURPOSE)
Зачем постоянно списки в сеты конвертировать?

2023-03-12 23:36 UTC, zhPavel commented on vitya/payment_order/payments/validators.py
> +    )
А что не использовать str.maketrans?

2023-03-12 23:36 UTC, zhPavel commented on vitya/payment_order/validators.py
> +        return 5
В типе надо Optional[str]

2023-03-12 23:36 UTC, zhPavel commented on vitya/payment_order/payments/payments.py
> +    _for_third_face: bool = False
Зачем его делать приватным?

2023-03-12 23:36 UTC, zhPavel commented on vitya/payment_order/payments/payments.py
> +    payer_bank_bic: Bic
![image](https://user-images.githubusercontent.com/46606586/224580329-5df9822e-7aec-48d2-add5-ab637be47113.png)
Где?

2023-03-12 23:36 UTC, zhPavel commented on vitya/payment_order/payments/payments.py
> +    payer_bank_account: str = Field(max_length=20, min_length=20)
![image](https://user-images.githubusercontent.com/46606586/224580407-6983152e-5c1d-4fa3-ada8-c194809174c4.png)
Где?

2023-03-12 23:36 UTC, zhPavel commented on vitya/payment_order/payments/payments.py
> +    payment_expire_days: Optional[int]
![image](https://user-images.githubusercontent.com/46606586/224580496-8202988b-5e0e-4a80-bfd2-ffa8f33cdeba.png)
Где?

2023-03-12 23:36 UTC, zhPavel commented on vitya/payment_order/payments/payments.py
> +    creation_date: date
![image](https://user-images.githubusercontent.com/46606586/224580615-6ffa6a95-2aa0-44b9-9b56-6bb2fe0c4a30.png)

Я не очень представляю, что такими проверками делать. Внутри Хайсы мы будем использовать isoformat  эти проверки не актуальны. Но должны ли быть они реализованы в этом пакете, если мы принимаем эти даныне из сторонних источников?

2023-03-13 09:02 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    name: str = 'Платежное поручение'
это общая либа - не используешь поля - не трогаешь их и все

2023-03-13 09:03 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    form: str = Field(max_length=6)
https://www.notion.so/hiceteam/d49c22ae200142c897061c3c23da397d?pvs=4

2023-03-13 09:03 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    amount_str: str = property(fget=lambda self: self.amount)  # type: ignore
это я исправлю да, надо тут использовать такуюе же любу как в пдф генераторе для слов

2023-03-13 09:04 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    _type: PaymentType
ну по хорошему нет - отвалидировал по типу поля и все. дальше платеж уже используешь как есть. ХЗ

2023-03-13 09:05 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +    purpose = validate_purpose(_type=_type, value=purpose)
я специально использовал обычный чтобы простые валидации (str, int decimal) сразу прошли, а дальше уже такая валидация. разве не норм?

2023-03-13 09:05 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    def validate_data(cls, values: Dict[str, Any]) -> Dict[str, Any]:
он же сразу на все поля вызывается?

2023-03-13 09:07 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +    return value
`А где проверка "Счёт обязательно присутствует в Справочник Казнечейский счетов"?
`
я как эту валидацию засуну с оффлайн либу? ты видишь что там делается запрос во внешний мир чтобы получить csv для валидации? 

все валидации требующие инет, должны делаться в сервисах которые подключают либу

2023-03-13 09:07 UTC, doiodl commented on vitya/payment_order/enums.py
> +    tms = 'tms'  # бюджетный платеж в таможню
таможня - transbord managment system*** 
хз что предлагаешь?

2023-03-13 09:08 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +        raise UINValidationDigitsOnlyError
как ты это нашел еб

2023-03-13 09:08 UTC, doiodl commented on tests/payment_order/payments/test_validators.py
> +def test_validate_payer_inn(
он же покрываетс с 2 нулями в начале?

2023-03-13 09:09 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +        return '0'
так договорились с ребятами

2023-03-13 09:09 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +    )
что это? никогда не видел

2023-03-13 09:10 UTC, doiodl commented on vitya/payment_order/validators.py
> +        return 5
ты уверен что не путаешь?

2023-03-13 09:10 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    _for_third_face: bool = False
зачем это поле нужно пользователю? оно используется толлько для валидацции

2023-03-13 09:11 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    payer_bank_bic: Bic
это общая либа 
конкретное значение будет в сервисе

2023-03-13 09:11 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    payer_bank_account: str = Field(max_length=20, min_length=20)
это общая либа 
конкретное значение будет в сервисе

2023-03-13 09:11 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    payment_expire_days: Optional[int]
optional[int] - либо есть либо нет. все равно сервис не будет использовать

2023-03-13 09:12 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    creation_date: date
да проверки жесткие
все что связанно с хайсом - будет в конкретной реализации сервисов платажей

2023-03-13 09:19 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +    return value
`А где проверка "Не ключуется с биком банка получателя"?`
я даже не знал что-то об этом. Добавлю

2023-03-13 10:44 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    name: str = 'Платежное поручение'
ClassVar

2023-03-13 10:45 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    form: str = Field(max_length=6)
порешали

2023-03-13 10:54 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    _type: PaymentType
окей сделаем публичным - делаем пропертей - изменять после создания нельзя

2023-03-13 10:56 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    _type: PaymentType
решили что все поля не изменяемые через
class Config:
        allow_mutation = False

2023-03-13 11:33 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    def validate_data(cls, values: Dict[str, Any]) -> Dict[str, Any]:
порешали

2023-03-13 11:40 UTC, doiodl commented on vitya/payment_order/enums.py
> +    tms = 'tms'  # бюджетный платеж в таможню
customs

2023-03-13 11:43 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +        raise UINValidationDigitsOnlyError
re.match(r'^[0-9]+$', '0')

2023-03-13 12:07 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +        return '0'
ладно все '' и 0 -> null

2023-03-13 12:07 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    payer_inn: str
ладно все '' и 0 -> null

2023-03-13 19:32 UTC, zhPavel commented on vitya/payment_order/payments/validators.py
> +    return None if value in {'', ''} else value
```
return None if value in {'0', ''} else value
```

2023-03-13 21:02 UTC, zhPavel requested changes

2023-03-13 21:02 UTC, zhPavel commented on vitya/payment_order/payments/validators.py
> +    return None if value in {'', ''} else value
Но, вообще, я не понял, зачем эта функция нужна, у тебя ведь и так эти значения конвертируются в transform_zeros

2023-03-14 08:55 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +    return None if value in {'', ''} else value
на всякий - если вдруг метод вызовут отдельно от модели

2023-03-16 07:57 UTC, malik89303 commented on vitya/payment_order/errors.py
> +                   'uin must be non zero'
заверни в скобки зачем бэкслеши

2023-03-16 08:00 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    form: str = Field(max_length=6)
ссылка на номер пп а тут форма

2023-03-16 08:01 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    number: str
ограничение на длину?

2023-03-16 08:03 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    payer_bank_account: str = Field(max_length=20, min_length=20)
сначала минимальную границу потом максимальную надо указать, проще читается

2023-03-16 08:03 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    payee_bank_account: Optional[str]
а где правила на длину

2023-03-16 08:04 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    payee_account: str
базовые проверки по типу длины можно сюда вынести

2023-03-16 08:04 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    operation_kind: str
там есть список возможных значений, поч не валидируется?

2023-03-16 08:06 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    uin: Optional[str]
базовые проверки на длмну можно вынести сюда

2023-03-16 08:06 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    payee_inn: Optional[str]
базовые проверки на длину можно вынести сюда

2023-03-16 08:07 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    payer_status: Optional[str]
базовые правила по длине можно вынести сюда

2023-03-16 08:09 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    oktmo: Optional[str]
базовые ограничения на длину?

2023-03-16 08:09 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    document_number: Optional[str]
базовые ограничения?

2023-03-16 08:11 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +            _type = values['type']
а почему вот это все и то что ниже это не валидатор пидантика?

2023-03-16 08:11 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +        return v if v not in {'', '0'} else None
поч не replase_zero_to_none

2023-03-16 08:31 UTC, malik89303 commented
тесты лежат

2023-03-16 13:12 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +            _type = values['type']
какой валидатор пидантика?

2023-03-16 13:27 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    form: str = Field(max_length=6)
согласен. не то

2023-03-16 13:32 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    payee_bank_account: Optional[str]
я не видел в правилах валидации это условие на 20
надо?

2023-03-16 15:00 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    payee_account: str
зачем? я все равно функцию валидации написал

2023-03-16 15:01 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    operation_kind: str
только для бюджета указаны какие.  что ты хочешь?

2023-03-16 15:11 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    oktmo: Optional[str]
длинная разная в зависимости от вида платежа?

2023-03-22 14:44 UTC, zhPavel requested changes

2023-03-22 14:44 UTC, zhPavel commented on vitya/payment_order/payments/checkers.py
> +    __checkers__: ClassVar[List[Tuple[Type[BaseChecker], str, ...]]] = []  # type: ignore
Аннотация неверная. Либо тапл известного размера -- Tuple[A, B], либо неизвестного -- Tuple[A, ...]

2023-03-22 14:44 UTC, zhPavel commented on vitya/payment_order/payments/payments.py
> +        (UinChecker, 'uin', 'payer_inn', 'payer_status', 'type'),  # type: ignore
Почему тут игнор типов?

2023-03-23 12:31 UTC, malik89303 commented on tests/payment_order/payments/test_validators.py
> +    if exception:
передавай хендлер в качестве параметра либо nullcontext() если эксепшон не ожидается, лишняя строчка пропадет

2023-03-23 12:32 UTC, malik89303 commented on tests/payment_order/payments/test_validators.py
> +    if exception:
это ко всем тестам относится

2023-03-23 12:34 UTC, malik89303 commented on vitya/payment_order/fields.py
> +    """Получатель (в названии должен содержать счета)"""
что занчит "в названии должен содержать счета"?

2023-03-23 12:36 UTC, malik89303 commented on vitya/payment_order/payments/checkers.py
> +            raise ValueError(errors)
а как отловить нужный эксепшон то?
тут нужны exceptiongroups которые в 3.11 появились
для старых питонов должна быть либа какая-то

2023-03-23 12:37 UTC, malik89303 commented on vitya/payment_order/payments/checkers.py
> +    def __init__(self, account_number: str, bic: Bic) -> None:
а почему account_number это str а  не AccountNumber

2023-03-23 12:37 UTC, malik89303 commented on vitya/payment_order/payments/checkers.py
> +        validate_operation_kind(value=self.operation_kind, _type=self.type)
почему operation_kind это str

2023-03-23 12:37 UTC, malik89303 commented on vitya/payment_order/payments/checkers.py
> +    def __init__(self, payer_inn: Inn, payer_status: str, for_third_face: bool, _type: PaymentType) -> None:
почему payer_status это str

2023-03-23 12:38 UTC, malik89303 commented on vitya/payment_order/payments/checkers.py
> +        self.uin = uin
uin str? 
payer status str?

2023-03-23 12:38 UTC, malik89303 commented on vitya/payment_order/payments/checkers.py
> +    def __init__(self, purpose: str, _type: PaymentType) -> None:
purpose str?

2023-03-23 12:38 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +class Payment(BaseModelChecker):
зачем это надо в либе?

2023-03-23 12:38 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    kind: str
поч стр

2023-03-23 12:39 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    amount_str: str = property(fget=lambda self: self.amount)  # type: ignore
а че не исправил то

2023-03-23 12:39 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    payer_status: Optional[str]
и по тому какие статусы возможны

2023-03-23 12:40 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    payee_kpp: Optional[str]
ты обещал удалить из этого пр все что с ним не связано

2023-03-23 12:40 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +    oktmo: Optional[str]
провалидируй то что длина находится среди допустимых

2023-03-23 12:40 UTC, malik89303 commented on vitya/payment_order/payments/validators.py
> +        if value != '03100643000000018500':
это константа должны быть ядум где-то вынесена

2023-03-23 12:46 UTC, doiodl commented on vitya/payment_order/payments/checkers.py
> +            raise ValueError(errors)
так можно будет вытащить внутри ошибки список ошибок - я уже это проверил

2023-03-23 12:48 UTC, doiodl commented on vitya/payment_order/payments/checkers.py
> +            raise ValueError(errors)
ты никак не зарейзишь несколько ошибок в старых питонах (в новом я знаю про группы)

2023-03-23 12:49 UTC, doiodl commented on vitya/payment_order/payments/checkers.py
> +    def __init__(self, account_number: str, bic: Bic) -> None:
потому что он валидирует строку, в чем вопрос?

2023-03-23 12:50 UTC, doiodl commented on vitya/payment_order/payments/checkers.py
> +        validate_operation_kind(value=self.operation_kind, _type=self.type)
потому что он валидирует строку

2023-03-23 12:51 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    form: str
потому что у него валидации? ты хочешь class Form(str) в котором ничего не делается?

2023-03-23 12:52 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +class Payment(BaseModelChecker):
Почему бы и нет? готовая модель

2023-03-23 12:56 UTC, malik89303 commented on vitya/payment_order/payments/checkers.py
> +            raise ValueError(errors)
https://pypi.org/project/exceptiongroup/

2023-03-23 12:57 UTC, malik89303 commented on vitya/payment_order/payments/payments.py
> +class Payment(BaseModelChecker):
не существует готовой модели для платежа, она разная для разных процессов всегда

2023-03-23 12:58 UTC, zhPavel commented on vitya/payment_order/payments/payments.py
> +    amount_str: str = property(fget=lambda self: self.amount)  # type: ignore
Пообщал, что в будущих пр-ах исправит

2023-03-23 13:19 UTC, doiodl commented on vitya/payment_order/payments/checkers.py
> +            raise ValueError(errors)
ну и зачем эта наслойка? то есть тот кто юзает либо должен использовать catch? что за бред + pydantic все равно все обернет в 1 ошибку кажется

2023-03-23 13:24 UTC, malik89303 commented on vitya/payment_order/payments/checkers.py
> +    def __init__(self, operation_kind: str, _type: PaymentType) -> None:
не понял почему везде вместо payment_type написано  _type

2023-03-23 15:35 UTC, malik89303 commented on vitya/payment_order/payments/validators.py
> +            raise PayeeAccountValidationBICValueError from e
не тестится кста

2023-03-23 15:35 UTC, malik89303 commented on vitya/payment_order/payments/validators.py
> +        raise INNValidationControlSumError
не тестится и не используется

2023-03-23 15:36 UTC, malik89303 commented on vitya/payment_order/payments/checkers.py
> +                continue
а где тесты на весь этот файл?

2023-03-23 15:37 UTC, malik89303 commented on vitya/payment_order/validators.py
> +        raise UINValidationControlSumError
не тестится

2023-03-24 08:57 UTC, doiodl commented on vitya/payment_order/payments/payments.py
> +    amount_str: str = property(fget=lambda self: self.amount)  # type: ignore
я удалили воообще это поле

2023-03-24 08:58 UTC, doiodl commented on vitya/payment_order/payments/checkers.py
> +            raise ValueError(errors)
а как ты работаешь с обычной моделью pydantic когда у нее несколько полей ломается?

2023-04-11 16:40 UTC, merged