HB-4558
hicebank/vitya pull request #23
Opened 2023-03-21 13:46 UTC by doiodl

2023-04-06 15:20 UTC, zhPavel requested changes

2023-04-06 15:56 UTC, WhiteApfel commented on vitya/payment_order/payments/validators.py
> +        raise OktmoValidationZerosNotAllowed
@zhPavel, оно либо "0", либо строка, в которой есть хотя бы одна ненулевая цифра

2023-04-06 18:17 UTC, WhiteApfel commented on vitya/payment_order/payments/validators.py
> +    value: Optional[Oktmo],
А сюда может (в значении должен) упасть "0"? Ведь ОКТМО в платёжке может принимать нулевое значение, а вот реальный ОКТМО строго 8/11 символов. Или это будет None? Но в платёжном поручении именно "0". А в объект Oktmo он не сможет превраиться из строки из-за своей длины. Поискал и не нашёл, где происходит эта подмена входных данных

2023-04-10 09:55 UTC, zhPavel commented on vitya/payment_order/payments/validators.py
> +    value: Optional[Oktmo],
Нулевой октмо -- это будет None. Преобразование будет не в библиотеке, а там, где происходит сопряжение в другими системами илли пользовательский ввод

2023-04-10 10:01 UTC, WhiteApfel commented on vitya/payment_order/payments/validators.py
> +    value: Optional[Oktmo],
Разве суть не в том, что должен получиться объект платёжного поручения, который должен содержать "0" вместо None? Да, по коду уже есть требования приведения к only-digits формату, но, тем не менее, это сырые данные, которые приходят из агрессивной внешней банковской среды. А тут мы такие "А вот это поле вы должны сами руками привести в None"

2023-04-10 11:03 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +            return value
узнаю

2023-04-10 11:35 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +            raise DocumentNumberValidationCustoms00ValueError
тут сказали что должно быть равно строго "00"

2023-04-10 11:36 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +    return value
засунул в проверку Inn

2023-04-10 11:59 UTC, doiodl commented on vitya/payment_order/payments/validators.py
> +            return value
аналитика сказала, что названия поля (дата) никак не отражает ее содержимое, и вообще придумано для человека-понимания. ЦБ пофиг - для них это 109 поле. Его содержимое строка - валидируемая задаваемыми правилами. Что лежит в нем (дата в формате каком-то) - нас не волнует.

2023-04-11 07:15 UTC, malik89303 commented on tests/payment_order/payments/test_checkers.py
> +            raise NotImplementedError
это что? почему не assert exception is None?
ниже везде аналогично

2023-04-11 07:16 UTC, malik89303 commented on tests/payment_order/payments/test_checks.py
> +    'value, payment_type, payer_status, for_third_face, exception_handler, expected_value',
выше и ниже аналогично

2023-04-11 07:18 UTC, malik89303 commented on vitya/payment_order/payments/checkers.py
> +            )
таб назад

2023-04-11 07:18 UTC, malik89303 commented on vitya/payment_order/payments/checkers.py
> +            )
таб назад

2023-04-11 07:21 UTC, malik89303 commented on vitya/payment_order/payments/helpers.py
> +    '22',
а может быть это енамы

2023-04-11 07:21 UTC, malik89303 commented on vitya/pydantic_fields.py
> +        return validate_oktmo(value)
поч не _validate_wrapper

2023-04-11 10:52 UTC, doiodl commented on vitya/payment_order/fields.py
> +class Cbc(str):
нельзя капсом - не snake case будет + у тебя глобальные переменные пишутся капсом
не согласен - не буду делать

2023-04-11 10:52 UTC, doiodl commented on tests/payment_order/payments/test_checks.py
> +    'value, payment_type, payer_status, for_third_face, exception_handler, expected_value',
здесь читаемое же

2023-04-11 10:52 UTC, doiodl commented on tests/payment_order/payments/test_checkers.py
> +            raise NotImplementedError
не понял что ты имел ввиду

2023-04-11 10:53 UTC, doiodl commented on vitya/payment_order/payments/helpers.py
> +    '22',
зачем?

2023-04-11 10:54 UTC, doiodl commented on vitya/pydantic_fields.py
> +        return validate_oktmo(value)
посмотри как он устроен - он валидирует и отдает тоже самое значение

не хотел его трогать вообще + он упаковывает ошибки в один общий класс, что не удобно в нашем подходе

по хорошему надо было и Inn переписать чтоли

2023-04-11 10:59 UTC, doiodl commented on tests/payment_order/payments/test_checkers.py
> +            raise NotImplementedError
понял бро

2023-04-11 11:20 UTC, malik89303 commented on vitya/pydantic_fields.py
> +        return validate_oktmo(value)
да

2023-04-11 14:51 UTC, WhiteApfel commented on vitya/pydantic_fields.py
> +class OGRNIp(str):
А чем ИП -- не аббревиатура?

2023-04-11 14:54 UTC, WhiteApfel commented on vitya/validators.py
> +        return None
Протестую. '' и '0' -- это только про payment_order

Обычный валидатор обычного октмо не должен принимать такие значения.

2023-04-11 14:58 UTC, WhiteApfel commented on vitya/validators.py
> +        return None
Можно добавить аргумент `is_from_payment_order: bool = False` и проверять только если он True

2023-04-11 15:38 UTC, malik89303 commented on vitya/payment_order/payments/helpers.py
> +    '22',
хз мб и не надо

2023-04-11 16:09 UTC, malik89303 commented on tests/test_vitya.py
> +    INNIp,
IP ?

2023-04-11 16:09 UTC, malik89303 commented on tests/test_vitya.py
> +    OGRNIp,
IP ?

2023-04-11 16:15 UTC, malik89303 commented on vitya/payment_order/payments/checks.py
> +    OktmoValidationZerosNotAllowed,
капс

2023-04-11 16:15 UTC, malik89303 commented on vitya/payment_order/validators.py
> +    CbcValidationValueLenError,
капс

2023-04-11 16:16 UTC, malik89303 commented on tests/test_vitya.py
>  class OktmoModel(BaseModel):
капс тут и выше

2023-04-11 16:40 UTC, merged